//+------------------------------------------------------------------+
//|                                     Accelerator_Oscillator.mq5 |
//|                                      Generated by Antigravity AI |
//+------------------------------------------------------------------+
#property copyright "Antigravity AI"
#property link      ""
#property version   "1.00"

#include <Trade\Trade.mqh>

//--- 1. PARAMETER ---
input int    VolPeriod  = 3;      // Volumen-Filter Periode
input int    TpIndex    = 19;     // Take Profit (Index 1-67)
input int    SlIndex    = 10;     // Stop Loss (Index 1-67)
input double VolumeLots = 0.01;   // Lot-Groesse

//--- 2. INTERNE LOGIK & HANDLES ---
CTrade         trade;
int            ac_handle;
datetime       last_bar_time;

double         prozentWerte[68] = {
    0.0, 
    0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 
    0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00,
    1.10, 1.20, 1.30, 1.40, 1.50, 1.60, 1.70, 1.80, 1.90, 2.00,
    2.10, 2.20, 2.30, 2.40, 2.50,
    2.75, 3.00, 3.25, 3.50, 3.75, 4.00, 4.25, 4.50, 4.75, 5.00
};

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
  {
   ac_handle = iAC(_Symbol, _Period);
   trade.SetExpertMagicNumber(123456);
   last_bar_time = 0;
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   IndicatorRelease(ac_handle);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
  {
   datetime current_time = iTime(_Symbol, _Period, 0);
   if(current_time == last_bar_time) return;
   
   last_bar_time = current_time;
   
   // Dynamische Arrays für Timeseries
   double ac[];
   ArraySetAsSeries(ac, true);
   
   long tick_vol_array[];
   ArraySetAsSeries(tick_vol_array, true);
   
   // Kopiere Daten
   if(CopyBuffer(ac_handle, 0, 0, 3, ac) <= 0) return;
   if(CopyTickVolume(_Symbol, _Period, 0, VolPeriod + 2, tick_vol_array) <= 0) return;
   
   // SMA des Volumens berechnen
   double vol_sum = 0;
   for(int i = 1; i <= VolPeriod; i++) {
       vol_sum += (double)tick_vol_array[i];
   }
   double vol_sma_1 = vol_sum / VolPeriod;
   double vol_1 = (double)tick_vol_array[1];
   
   bool acBullish = ac[1] > ac[2] && ac[1] > 0;
   bool acBearish = ac[1] < ac[2] && ac[1] < 0;
   bool volumeConfirm = vol_1 > vol_sma_1;
   
   bool longSignal = acBullish && volumeConfirm;
   bool shortSignal = acBearish && volumeConfirm;
   
   if(longSignal && !HasOpenPosition(POSITION_TYPE_BUY))
     {
      ClosePositionsByDirection(POSITION_TYPE_SELL);
      ExecuteOrder(ORDER_TYPE_BUY);
     }
   else if(shortSignal && !HasOpenPosition(POSITION_TYPE_SELL))
     {
      ClosePositionsByDirection(POSITION_TYPE_BUY);
      ExecuteOrder(ORDER_TYPE_SELL);
     }
  }

//+------------------------------------------------------------------+
//| Custom functions                                                 |
//+------------------------------------------------------------------+
bool HasOpenPosition(ENUM_POSITION_TYPE type)
  {
   for(int i=PositionsTotal()-1; i>=0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
        {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_TYPE) == type)
            return true;
        }
     }
   return false;
  }

void ClosePositionsByDirection(ENUM_POSITION_TYPE type)
  {
   for(int i=PositionsTotal()-1; i>=0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(PositionSelectByTicket(ticket))
        {
         if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_TYPE) == type)
           {
            trade.PositionClose(ticket);
           }
        }
     }
  }

void ExecuteOrder(ENUM_ORDER_TYPE type)
  {
   double currentPrice = (type == ORDER_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double point = SymbolInfoDouble(_Symbol, SYMBOL_POINT);
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   double pipSize = point * ((digits == 5 || digits == 3) ? 10 : 1);
   
   int actualTpIndex = TpIndex;
   int actualSlIndex = SlIndex;
   
   string sym = _Symbol;
   if(StringFind(sym, "USD") >= 0 || StringFind(sym, "EUR") >= 0)
     {
      if(actualTpIndex > 45) actualTpIndex = 45;
      if(actualSlIndex > 45) actualSlIndex = 45;
     }
     
   double echterTpProzent = prozentWerte[actualTpIndex];
   double echterSlProzent = prozentWerte[actualSlIndex];
   
   double tpPips = (currentPrice * (echterTpProzent / 100.0)) / pipSize;
   double slPips = (currentPrice * (echterSlProzent / 100.0)) / pipSize;
   
   double slPrice = 0;
   double tpPrice = 0;
   
   if(type == ORDER_TYPE_BUY)
     {
      slPrice = currentPrice - (slPips * pipSize);
      tpPrice = currentPrice + (tpPips * pipSize);
      trade.Buy(VolumeLots, _Symbol, currentPrice, slPrice, tpPrice, "Accelerator_006");
     }
   else
     {
      slPrice = currentPrice + (slPips * pipSize);
      tpPrice = currentPrice - (tpPips * pipSize);
      trade.Sell(VolumeLots, _Symbol, currentPrice, slPrice, tpPrice, "Accelerator_006");
     }
  }

//+------------------------------------------------------------------+
//| Tester Functions for CSV Generation                              |
//+------------------------------------------------------------------+



string GetStrategyName() { return "Accelerator_Oscillator"; }
int GetStrategyNum() { return 0; }
void GetStrategyParameters(double &params[])
{
   ArrayResize(params, 10);
   ArrayInitialize(params, 0.0);
   params[0] = (double)VolPeriod;
}

#include <MetricsOutput.mqh>
